language: java
jdk:
  - oraclejdk8

services:
  - oracle

env:
  global:
    - ORACLE_URL=jdbc:oracle:thin:@edudb_high?TNS_ADMIN=C:/dev64/Wallet_edudb
    - ORACLE_USER=CSW2YA
    - ORACLE_PASSWORD=Qwerty123456

before_install:
  - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc

install: true

script:
  - mvn clean install -DskipTests=false

before_deploy:
  - zip -r FinalProject
  - mkdir -p deploy
  - mv FinalProject.zip deploy/FinalProject.zip

deploy:
  - provider: s3
    access_key_id: AKIASMEPUQWCQSL2IUPJ
    secret_access_key: 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
    bucket: thechefbucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - oneheal57@gmail.com